version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: employee,vacation
    ports:
      - 5431:5432
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - corpbot-network
      
  hazelcast:
    image: hazelcast/hazelcast:5.1.3
    ports:
      - 5701:5701
      - 5702:5702
      - 5703:5703
    networks:
      - corpbot-network

networks:
  corpbot-network:
    driver: bridge